In [1]:
import pandas as pd

In [8]:
data_deaths=pd.read_csv('Number of deaths by cause, World, 1990 to 2019.csv', sep=';')

In [9]:
print(data_deaths)

            Entity  Code   Year Number of executions (Amnesty International)  \
0     Afghanis;tan  AFG;   2007                                           15
1     Afghanis;tan  AFG;   2008                                           17
2     Afghanis;tan  AFG;   2009                                            0
3     Afghanis;tan  AFG;   2011                                            2
4     Afghanis;tan  AFG;   2012                                           14
...            ...   ...    ...                                          ...
7268     Zimbabwe;   ZWE  20;15                                          NaN
7269     Zimbabwe;   ZWE  20;16                                          NaN
7270     Zimbabwe;   ZWE  20;17                                          NaN
7271     Zimbabwe;   ZWE  20;18                                          NaN
7272     Zimbabwe;   ZWE  20;19                                          NaN

     Deaths - Meningitis - Sex: Both - Age: All Ages (Number)  \
0                                                  2933
1                                                  2731
2                                                  2460
3                                                  2327
4                                                  2254
...                                                 ...
7268                                               1439
7269                                               1457
7270                                               1460
7271                                               1450
7272                                               1450

      Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number)  \
0                                                1402.0
1                                                1424.0
2                                                1449.0
3                                                1508.0
4                                                1544.0
...                                                 ...
7268                                              754.0
7269                                              767.0
7270                                              781.0
7271                                              795.0
7272                                              812.0

     Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number)  \
0                                                   450
1                                                   455
2                                                   460
3                                                   473
4                                                   482
...                                                 ...
7268                                                215
7269                                                219
7270                                                223
7271                                                227
7272                                                232

      Deaths - Nutritional deficiencies - Sex: Both - Age: All Ages (Number)  \
0                                                2488.0
1                                                2277.0
2                                                2040.0
3                                                1846.0
4                                                1705.0
...                                                 ...
7268                                             3019.0
7269                                             3056.0
7270                                             2990.0
7271                                             2918.0
7272                                             2884.0

      Deaths - Malaria - Sex: Both - Age: All Ages (Number)  \
0                                                 393.0
1                                                 255.0
2                                                 239.0
3                                                 390.0
4                                                  94.0
...                                                 ...
7268                                             2518.0
7269                                             2050.0
7270                                             2116.0
7271                                             2088.0
7272                                             2068.0

      Deaths - Drowning - Sex: Both - Age: All Ages (Number)  ...  \
0                                                2127.0       ...
1                                                1973.0       ...
2                                                1852.0       ...
3                                                1775.0       ...
4                                                1716.0       ...
...                                                 ...       ...
7268                                              770.0       ...
7269                                              801.0       ...
7270                                              818.0       ...
7271                                              825.0       ...
7272                                              827.0       ...

      Unnamed: 26  Unnamed: 27  Unnamed: 28  Unnamed: 29  Unnamed: 30  \
0          4490.0        513.0       2439.0       1199.0       7425.0
1          4534.0        495.0       2231.0       1092.0       7355.0
2          4597.0        483.0       1998.0       1065.0       7290.0
3          4785.0        483.0       1805.0       1525.0       7432.0
4          4846.0        482.0       1667.0       3521.0       7494.0
...           ...          ...          ...          ...          ...
7268       2108.0        381.0       2990.0          NaN       2373.0
7269       2160.0        393.0       3027.0          NaN       2436.0
7270       2196.0        398.0       2962.0          0.0       2473.0
7271       2240.0        400.0       2890.0          NaN       2509.0
7272       2292.0        405.0       2855.0          NaN       2554.0

      Unnamed: 31  Unnamed: 32  Unnamed: 33  Unnamed: 34  Unnamed: 35
0          7222.0       3346.0       6458.0        481.0       3437.0
1          7143.0       3316.0       6408.0        462.0       3005.0
2          7045.0       3291.0       6358.0        448.0       2663.0
3          6916.0       3318.0       6370.0        448.0       2365.0
4          6878.0       3353.0       6398.0        445.0       2264.0
...           ...          ...          ...          ...          ...
7268       2751.0       1956.0       4202.0        632.0        146.0
7269       2788.0       1962.0       4264.0        648.0        146.0
7270       2818.0       2007.0       4342.0        654.0        144.0
7271       2849.0       2030.0       4377.0        657.0        139.0
7272       2891.0       2065.0       4437.0        662.0        136.0

[7273 rows x 36 columns]

In [10]:
data_deaths['Entity'] = data_deaths['Entity'].str.replace(';','')

In [11]:
print(data_deaths)

           Entity  Code   Year Number of executions (Amnesty International)  \
0     Afghanistan  AFG;   2007                                           15
1     Afghanistan  AFG;   2008                                           17
2     Afghanistan  AFG;   2009                                            0
3     Afghanistan  AFG;   2011                                            2
4     Afghanistan  AFG;   2012                                           14
...           ...   ...    ...                                          ...
7268     Zimbabwe   ZWE  20;15                                          NaN
7269     Zimbabwe   ZWE  20;16                                          NaN
7270     Zimbabwe   ZWE  20;17                                          NaN
7271     Zimbabwe   ZWE  20;18                                          NaN
7272     Zimbabwe   ZWE  20;19                                          NaN

     Deaths - Meningitis - Sex: Both - Age: All Ages (Number)  \
0                                                  2933
1                                                  2731
2                                                  2460
3                                                  2327
4                                                  2254
...                                                 ...
7268                                               1439
7269                                               1457
7270                                               1460
7271                                               1450
7272                                               1450

      Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number)  \
0                                                1402.0
1                                                1424.0
2                                                1449.0
3                                                1508.0
4                                                1544.0
...                                                 ...
7268                                              754.0
7269                                              767.0
7270                                              781.0
7271                                              795.0
7272                                              812.0

     Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number)  \
0                                                   450
1                                                   455
2                                                   460
3                                                   473
4                                                   482
...                                                 ...
7268                                                215
7269                                                219
7270                                                223
7271                                                227
7272                                                232

      Deaths - Nutritional deficiencies - Sex: Both - Age: All Ages (Number)  \
0                                                2488.0
1                                                2277.0
2                                                2040.0
3                                                1846.0
4                                                1705.0
...                                                 ...
7268                                             3019.0
7269                                             3056.0
7270                                             2990.0
7271                                             2918.0
7272                                             2884.0

      Deaths - Malaria - Sex: Both - Age: All Ages (Number)  \
0                                                 393.0
1                                                 255.0
2                                                 239.0
3                                                 390.0
4                                                  94.0
...                                                 ...
7268                                             2518.0
7269                                             2050.0
7270                                             2116.0
7271                                             2088.0
7272                                             2068.0

      Deaths - Drowning - Sex: Both - Age: All Ages (Number)  ...  \
0                                                2127.0       ...
1                                                1973.0       ...
2                                                1852.0       ...
3                                                1775.0       ...
4                                                1716.0       ...
...                                                 ...       ...
7268                                              770.0       ...
7269                                              801.0       ...
7270                                              818.0       ...
7271                                              825.0       ...
7272                                              827.0       ...

      Unnamed: 26  Unnamed: 27  Unnamed: 28  Unnamed: 29  Unnamed: 30  \
0          4490.0        513.0       2439.0       1199.0       7425.0
1          4534.0        495.0       2231.0       1092.0       7355.0
2          4597.0        483.0       1998.0       1065.0       7290.0
3          4785.0        483.0       1805.0       1525.0       7432.0
4          4846.0        482.0       1667.0       3521.0       7494.0
...           ...          ...          ...          ...          ...
7268       2108.0        381.0       2990.0          NaN       2373.0
7269       2160.0        393.0       3027.0          NaN       2436.0
7270       2196.0        398.0       2962.0          0.0       2473.0
7271       2240.0        400.0       2890.0          NaN       2509.0
7272       2292.0        405.0       2855.0          NaN       2554.0

      Unnamed: 31  Unnamed: 32  Unnamed: 33  Unnamed: 34  Unnamed: 35
0          7222.0       3346.0       6458.0        481.0       3437.0
1          7143.0       3316.0       6408.0        462.0       3005.0
2          7045.0       3291.0       6358.0        448.0       2663.0
3          6916.0       3318.0       6370.0        448.0       2365.0
4          6878.0       3353.0       6398.0        445.0       2264.0
...           ...          ...          ...          ...          ...
7268       2751.0       1956.0       4202.0        632.0        146.0
7269       2788.0       1962.0       4264.0        648.0        146.0
7270       2818.0       2007.0       4342.0        654.0        144.0
7271       2849.0       2030.0       4377.0        657.0        139.0
7272       2891.0       2065.0       4437.0        662.0        136.0

[7273 rows x 36 columns]

In [12]:
data_deaths['Code']=data_deaths['Code'].str.replace(';','')

In [13]:
print(data_deaths)

           Entity Code   Year Number of executions (Amnesty International)  \
0     Afghanistan  AFG   2007                                           15
1     Afghanistan  AFG   2008                                           17
2     Afghanistan  AFG   2009                                            0
3     Afghanistan  AFG   2011                                            2
4     Afghanistan  AFG   2012                                           14
...           ...  ...    ...                                          ...
7268     Zimbabwe  ZWE  20;15                                          NaN
7269     Zimbabwe  ZWE  20;16                                          NaN
7270     Zimbabwe  ZWE  20;17                                          NaN
7271     Zimbabwe  ZWE  20;18                                          NaN
7272     Zimbabwe  ZWE  20;19                                          NaN

     Deaths - Meningitis - Sex: Both - Age: All Ages (Number)  \
0                                                  2933
1                                                  2731
2                                                  2460
3                                                  2327
4                                                  2254
...                                                 ...
7268                                               1439
7269                                               1457
7270                                               1460
7271                                               1450
7272                                               1450

      Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number)  \
0                                                1402.0
1                                                1424.0
2                                                1449.0
3                                                1508.0
4                                                1544.0
...                                                 ...
7268                                              754.0
7269                                              767.0
7270                                              781.0
7271                                              795.0
7272                                              812.0

     Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number)  \
0                                                   450
1                                                   455
2                                                   460
3                                                   473
4                                                   482
...                                                 ...
7268                                                215
7269                                                219
7270                                                223
7271                                                227
7272                                                232

      Deaths - Nutritional deficiencies - Sex: Both - Age: All Ages (Number)  \
0                                                2488.0
1                                                2277.0
2                                                2040.0
3                                                1846.0
4                                                1705.0
...                                                 ...
7268                                             3019.0
7269                                             3056.0
7270                                             2990.0
7271                                             2918.0
7272                                             2884.0

      Deaths - Malaria - Sex: Both - Age: All Ages (Number)  \
0                                                 393.0
1                                                 255.0
2                                                 239.0
3                                                 390.0
4                                                  94.0
...                                                 ...
7268                                             2518.0
7269                                             2050.0
7270                                             2116.0
7271                                             2088.0
7272                                             2068.0

      Deaths - Drowning - Sex: Both - Age: All Ages (Number)  ...  \
0                                                2127.0       ...
1                                                1973.0       ...
2                                                1852.0       ...
3                                                1775.0       ...
4                                                1716.0       ...
...                                                 ...       ...
7268                                              770.0       ...
7269                                              801.0       ...
7270                                              818.0       ...
7271                                              825.0       ...
7272                                              827.0       ...

      Unnamed: 26  Unnamed: 27  Unnamed: 28  Unnamed: 29  Unnamed: 30  \
0          4490.0        513.0       2439.0       1199.0       7425.0
1          4534.0        495.0       2231.0       1092.0       7355.0
2          4597.0        483.0       1998.0       1065.0       7290.0
3          4785.0        483.0       1805.0       1525.0       7432.0
4          4846.0        482.0       1667.0       3521.0       7494.0
...           ...          ...          ...          ...          ...
7268       2108.0        381.0       2990.0          NaN       2373.0
7269       2160.0        393.0       3027.0          NaN       2436.0
7270       2196.0        398.0       2962.0          0.0       2473.0
7271       2240.0        400.0       2890.0          NaN       2509.0
7272       2292.0        405.0       2855.0          NaN       2554.0

      Unnamed: 31  Unnamed: 32  Unnamed: 33  Unnamed: 34  Unnamed: 35
0          7222.0       3346.0       6458.0        481.0       3437.0
1          7143.0       3316.0       6408.0        462.0       3005.0
2          7045.0       3291.0       6358.0        448.0       2663.0
3          6916.0       3318.0       6370.0        448.0       2365.0
4          6878.0       3353.0       6398.0        445.0       2264.0
...           ...          ...          ...          ...          ...
7268       2751.0       1956.0       4202.0        632.0        146.0
7269       2788.0       1962.0       4264.0        648.0        146.0
7270       2818.0       2007.0       4342.0        654.0        144.0
7271       2849.0       2030.0       4377.0        657.0        139.0
7272       2891.0       2065.0       4437.0        662.0        136.0

[7273 rows x 36 columns]

In [14]:
data_deaths['Year']=data_deaths['Year'].str.replace(';','')

In [15]:
print(data_deaths)

           Entity Code  Year Number of executions (Amnesty International)  \
0     Afghanistan  AFG  2007                                           15
1     Afghanistan  AFG  2008                                           17
2     Afghanistan  AFG  2009                                            0
3     Afghanistan  AFG  2011                                            2
4     Afghanistan  AFG  2012                                           14
...           ...  ...   ...                                          ...
7268     Zimbabwe  ZWE  2015                                          NaN
7269     Zimbabwe  ZWE  2016                                          NaN
7270     Zimbabwe  ZWE  2017                                          NaN
7271     Zimbabwe  ZWE  2018                                          NaN
7272     Zimbabwe  ZWE  2019                                          NaN

     Deaths - Meningitis - Sex: Both - Age: All Ages (Number)  \
0                                                  2933
1                                                  2731
2                                                  2460
3                                                  2327
4                                                  2254
...                                                 ...
7268                                               1439
7269                                               1457
7270                                               1460
7271                                               1450
7272                                               1450

      Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number)  \
0                                                1402.0
1                                                1424.0
2                                                1449.0
3                                                1508.0
4                                                1544.0
...                                                 ...
7268                                              754.0
7269                                              767.0
7270                                              781.0
7271                                              795.0
7272                                              812.0

     Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number)  \
0                                                   450
1                                                   455
2                                                   460
3                                                   473
4                                                   482
...                                                 ...
7268                                                215
7269                                                219
7270                                                223
7271                                                227
7272                                                232

      Deaths - Nutritional deficiencies - Sex: Both - Age: All Ages (Number)  \
0                                                2488.0
1                                                2277.0
2                                                2040.0
3                                                1846.0
4                                                1705.0
...                                                 ...
7268                                             3019.0
7269                                             3056.0
7270                                             2990.0
7271                                             2918.0
7272                                             2884.0

      Deaths - Malaria - Sex: Both - Age: All Ages (Number)  \
0                                                 393.0
1                                                 255.0
2                                                 239.0
3                                                 390.0
4                                                  94.0
...                                                 ...
7268                                             2518.0
7269                                             2050.0
7270                                             2116.0
7271                                             2088.0
7272                                             2068.0

      Deaths - Drowning - Sex: Both - Age: All Ages (Number)  ...  \
0                                                2127.0       ...
1                                                1973.0       ...
2                                                1852.0       ...
3                                                1775.0       ...
4                                                1716.0       ...
...                                                 ...       ...
7268                                              770.0       ...
7269                                              801.0       ...
7270                                              818.0       ...
7271                                              825.0       ...
7272                                              827.0       ...

      Unnamed: 26  Unnamed: 27  Unnamed: 28  Unnamed: 29  Unnamed: 30  \
0          4490.0        513.0       2439.0       1199.0       7425.0
1          4534.0        495.0       2231.0       1092.0       7355.0
2          4597.0        483.0       1998.0       1065.0       7290.0
3          4785.0        483.0       1805.0       1525.0       7432.0
4          4846.0        482.0       1667.0       3521.0       7494.0
...           ...          ...          ...          ...          ...
7268       2108.0        381.0       2990.0          NaN       2373.0
7269       2160.0        393.0       3027.0          NaN       2436.0
7270       2196.0        398.0       2962.0          0.0       2473.0
7271       2240.0        400.0       2890.0          NaN       2509.0
7272       2292.0        405.0       2855.0          NaN       2554.0

      Unnamed: 31  Unnamed: 32  Unnamed: 33  Unnamed: 34  Unnamed: 35
0          7222.0       3346.0       6458.0        481.0       3437.0
1          7143.0       3316.0       6408.0        462.0       3005.0
2          7045.0       3291.0       6358.0        448.0       2663.0
3          6916.0       3318.0       6370.0        448.0       2365.0
4          6878.0       3353.0       6398.0        445.0       2264.0
...           ...          ...          ...          ...          ...
7268       2751.0       1956.0       4202.0        632.0        146.0
7269       2788.0       1962.0       4264.0        648.0        146.0
7270       2818.0       2007.0       4342.0        654.0        144.0
7271       2849.0       2030.0       4377.0        657.0        139.0
7272       2891.0       2065.0       4437.0        662.0        136.0

[7273 rows x 36 columns]